### PR TITLE
Handle client configuration for different provider using connection plugin

### PR DESCRIPTION
**Pull request by abikouo**
##### SUMMARY
The `tests/integration/targets/connection` is just to demo how to use the connection plugin for now

### CODE REVIEW

**Comment by gravesm** [comment]
My main feedback with this is that I'd like for the resource definition to be pulled out of the host file and into a vars file.

**Comment by abikouo** [comment]
> My main feedback with this is that I'd like for the resource definition to be pulled out of the host file and into a vars file.

PR has been updated accordingly.

**Comment by gravesm** [comment]
Could you split the ADR out into a separate PR? I'd like to discuss that separately from the code.

**Comment by abikouo** [comment]
> Could you split the ADR out into a separate PR? I'd like to discuss that separately from the code.

Done
https://github.com/ansible-collections/pravic/pull/19

**Comment by abikouo** [comment]
recheck

**Pull request closed without merging**
